services:
  adam-api:
    container_name: adam-api
    build:
      context: .
      dockerfile: src/api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/adamdb.db;Cache=Shared
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /home/visnovskya:/app/data
